accelerator: gpu
devices: 1
enable_model_summary: false
log_every_n_steps: 1
check_val_every_n_epoch: 250
max_epochs: 3000

callbacks:
  - class_path: ModelCheckpoint
    init_args:
      verbose: true
      every_n_epochs: 100
      save_weights_only: false
      filename: "{epoch}-{val_loss:.4f}"

logger:
  - class_path: WandbLogger
    init_args:
      project: wandb-project
